development:
  adapter: mysql2
  database: test 
  username: root
  password: 
  socket: /tmp/mysql.sock
  encoding: utf8
  
production:
  adapter: mysql2
  database: test 
  username: root
  password: 
  socket: /tmp/mysql.sock
  encoding: utf8